development:
 adapter: postgresql
 encoding: unicode
 database: SecretSanta_development
 pool: 5
 timeout: 5000
 host: localhost
 username: mrgnwatson
 password:

test:
 adapter: postgresql
 encoding: unicode
 database: SecretSanta_test
 pool: 5
 timeout: 5000
 host: localhost
 username: mrgnwatson
 password:

production:
 adapter: postgresql
 encoding: unicode
 database: SecretSanta_production
 pool: 5